/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/sign-up/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Signup */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "X-Powered-By"?: string;
                        "Access-Control-Allow-Origin"?: string;
                        "Content-Type"?: string;
                        Etag?: string;
                        "Function-Execution-Id"?: string;
                        "X-Cloud-Trace-Context"?: string;
                        Date?: string;
                        Server?: string;
                        "Content-Length"?: number;
                        "Alt-Svc"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-season/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 최신 기수 정보 조회 (From Admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-auth/verify/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 인증 코드 전송 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "X-Powered-By"?: string;
                        "Access-Control-Allow-Origin"?: string;
                        "Content-Type"?: string;
                        Etag?: string;
                        "Function-Execution-Id"?: string;
                        "X-Cloud-Trace-Context"?: string;
                        Date?: string;
                        Server?: string;
                        "Content-Length"?: number;
                        "Alt-Svc"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-auth/verify/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 인증 코드 확인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 지원자 회원가입 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-auth/check/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 유저 확인 (비밀번호 변경) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-auth/change/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 비밀번호 변경 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-question/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 질문 리스트 조회 (From Admin) */
        get: {
            parameters: {
                query?: {
                    /** @example 52 */
                    season?: number;
                    /** @example OB */
                    group?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-answer/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 임시저장 지원서 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        "X-Powered-By"?: string;
                        "Access-Control-Allow-Origin"?: string;
                        "Content-Type"?: string;
                        Etag?: string;
                        "Function-Execution-Id"?: string;
                        "X-Cloud-Trace-Context"?: string;
                        Date?: string;
                        Server?: string;
                        "Content-Length"?: number;
                        "Alt-Svc"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        /** 지원서 임시저장 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        picture?: string;
                        /**
                         * @description string
                         * @example 서버
                         */
                        part?: string;
                        /**
                         * @description string
                         * @example home1
                         */
                        address?: string;
                        /**
                         * @description string
                         * @example 2001.01.23
                         */
                        birthday?: number;
                        /**
                         * @description string
                         * @example 대학
                         */
                        college?: string;
                        /**
                         * @description string
                         * @example male
                         */
                        gender?: string;
                        /**
                         * @description string
                         * @example 지인 추천
                         */
                        knownPath?: string;
                        /**
                         * @description bool
                         * @example false
                         */
                        leaveAbsence?: boolean;
                        /**
                         * @description string
                         * @example 통계
                         */
                        major?: string;
                        /**
                         * @description int
                         * @example 0
                         */
                        mostRecentSeason?: number;
                        /**
                         * @description int
                         * @example 4
                         */
                        univYear?: number;
                        /**
                         * @description string
                         * @example 사당역
                         */
                        nearestStation?: string;
                        /**
                         * @description json
                         * @example [
                         *       {
                         *         "recruitingQuestionId": 1,
                         *         "answer": "5그릇"
                         *       },
                         *       {
                         *         "recruitingQuestionId": 2,
                         *         "answer": "4그릇"
                         *       }
                         *     ]
                         */
                        answers?: string;
                        /**
                         * @description bool
                         * @example false
                         */
                        willAppjam?: boolean;
                        /** Format: binary */
                        file_28?: string;
                        /** Format: binary */
                        file_29?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        "X-Powered-By"?: string;
                        "Access-Control-Allow-Origin"?: string;
                        "Content-Type"?: string;
                        Etag?: string;
                        "Function-Execution-Id"?: string;
                        "X-Cloud-Trace-Context"?: string;
                        Date?: string;
                        Server?: string;
                        "Content-Length"?: number;
                        "Alt-Svc"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 지원서 제출 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        picture?: string;
                        /**
                         * @description string
                         * @example 서버
                         */
                        part?: string;
                        /**
                         * @description string
                         * @example home1
                         */
                        address?: string;
                        /**
                         * @description string
                         * @example 2001.01.23
                         */
                        birthday?: number;
                        /**
                         * @description string
                         * @example 대학
                         */
                        college?: string;
                        /**
                         * @description string
                         * @example male
                         */
                        gender?: string;
                        /**
                         * @description string
                         * @example 지인 추천
                         */
                        knownPath?: string;
                        /**
                         * @description bool
                         * @example false
                         */
                        leaveAbsence?: boolean;
                        /**
                         * @description string
                         * @example 통계
                         */
                        major?: string;
                        /**
                         * @description string
                         * @example 0
                         */
                        mostRecentSeason?: number;
                        /**
                         * @description int
                         * @example 4
                         */
                        univYear?: number;
                        /**
                         * @description string
                         * @example 사당역
                         */
                        nearestStation?: string;
                        /**
                         * @description json
                         * @example [
                         *       {
                         *         "recruitingQuestionId": 1,
                         *         "answer": "5그릇"
                         *       },
                         *       {
                         *         "recruitingQuestionId": 2,
                         *         "answer": "4그릇"
                         *       }
                         *     ]
                         */
                        answers?: string;
                        /**
                         * @description bool
                         * @example false
                         */
                        willAppjam?: boolean;
                        /** @example 1 */
                        season?: number;
                        /** @example OB */
                        group?: string;
                        pictureUrl?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        "X-Powered-By"?: string;
                        "Access-Control-Allow-Origin"?: string;
                        "Content-Type"?: string;
                        Etag?: string;
                        "Function-Execution-Id"?: string;
                        "X-Cloud-Trace-Context"?: string;
                        Date?: string;
                        Server?: string;
                        "Content-Length"?: number;
                        "Alt-Svc"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-applicant/satisfaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 만족도 점수 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-auth/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 마이페이지 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        "X-Powered-By"?: string;
                        "Access-Control-Allow-Origin"?: string;
                        "Content-Type"?: string;
                        Etag?: string;
                        "Function-Execution-Id"?: string;
                        "X-Cloud-Trace-Context"?: string;
                        Date?: string;
                        Server?: string;
                        "Content-Length"?: number;
                        "Alt-Svc"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-applicant/result/application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 마이페이지 서류 합격 확인 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruiting-applicant/result/final": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 마이페이지 최종 합격 확인 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        "x-powered-by"?: string;
                        "access-control-allow-origin"?: string;
                        "content-type"?: string;
                        "content-length"?: number;
                        etag?: string;
                        date?: string;
                        connection?: string;
                        "keep-alive"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
